[package]
name = "rs_loader_impl"
version = "0.1.0"
edition = "2022"

[lib]
name = "rs_loader_impl"
crate-type = ["cdylib"]

[package.metadata.rust-analyzer]
rustc_private = true

[profile.release]
opt-level = "z"

[workspace]
members = ["api", "compiler"]

[dependencies]
api = { path = "./api" }
compiler = { path = "./compiler" }
