[package]
name = "metacall"
version = "0.2.1"
repository = "https://github.com/metacall/core/tree/develop/source/ports/rs_port"
authors = ["Vicente Eduardo Ferrer Garcia <vic798@gmail.com>", "Swarnim Arun <swarnimarun11@gmail.com>"]
edition = "2022"
license = "Apache-2.0"
readme = "README.md"
description = "Call NodeJS, TypeScript, Python, C#, Ruby... functions from Rust (a Rust Port for MetaCall)."

[lib]
name = "metacall"
crate-type = ["lib"] # TODO: Once this is unified with the loader, we should use cdylib type
path = "src/lib.rs"
edition = "2022"

[dependencies]
abi = { path = "./abi" }
inline = { path = "./inline" }
